{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx instance working",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Connections handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled[5m])"
    }
   ]
  }
 ]
}