---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  mysite.conf: |
    server {

      listen {{ .Values.nginx.servicePort }};
      server_name {{ .Values.ingress.host }};

      location / {
        deny 192.168.10.0/24;
        root  /usr/share/nginx/site;
        index index.html;
        # try_files $uri $uri/ /index.html;
      }

      location /nginx_status {
        stub_status;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-html
data:
  index.html: |
    Hello World!