---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
        - image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          name: {{ .Chart.Name }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.nginx.containerPort }}
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
          - name: html
            mountPath: /usr/share/nginx/site/
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.10.0'
          args:
            - '-nginx.scrape-uri=http://localhost/metrics'
          ports:
          - name: nginx-ex-port
            containerPort: 9113
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ .Chart.Name }}-config
      - name: html
        configMap:
          name: {{ .Chart.Name }}-html