apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx-service
spec:
  ports:
    - port: {{ .Values.nginx.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.nginx.containerPort }}
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-nginx